### PR TITLE
Add possibility to set custom font to the links

### PR DESCRIPTION
**Pull request by merzal**
I need to set custom font to the link of the active text, e.g. to the 'Sign up' part:

Screenshot 2022-04-29 at 16 11 42

With this addition DSKit will be able to do that.

### CODE REVIEW

**Comment by imodeveloper** [comment]
@merzal this implementation is breaking the default use of links for **DSActiveTextVM** 
Was:
reference_1_CE90F55A-3DC3-478D-9D15-D2C75EBFCD3B

Now: 
failure_2_CE90F55A-3DC3-478D-9D15-D2C75EBFCD3B

you can see that test **testTypographyActiveText** from **TypographyLayoutTests** fail to pass.

**Review by imodeveloper — CHANGES_REQUESTED** [review]
We need to keep old implementation.

**Comment by merzal** [comment]
Done.

**Comment by imodeveloper** [comment]
I tried this example 

```swift
var activeText2 = DSActiveTextVM(.body, text: "Dont have an account yet? Sign up")
        activeText2.linksFont = .headline
        activeText2.links = ["Sign up": "https://dskit.app"]
        activeText2.didTapOnUrl = { url in
            self.show(message: "Did tap on url:\(url.absoluteString)")
        }
        
show(content: activeText2)
```
Result:
Screenshot 2022-05-03 at 16 50 52

**Comment by merzal** [comment]
Yeah, that was exactly my goal: to be able to use different font for the links in the active texts.

With this I could reach my original goal. Now I can define custom font (in this case a semibold version of the original font) for my 'Sign up' part:

165969407-6c1a4226-aff8-4550-b829-f3970245909b

**Comment by imodeveloper** [comment]
@merzal  can you try this code, it seems more natural to use for your case. 

```swift 
let text = DSTextComposer(alignment: .center)
text.add(type: .body, text: "Dont have an account yet? ")
text.add(type: .headline, text: "Sign up!", newLine: false)
var model = text.textViewModel()
model.didTap { model in
    print(model)
}

show(content: model)
```
**Result:**

Screenshot 2022-05-03 at 17 44 16

**Comment by merzal** [comment]
You are right, this could work. But!

I have 2 issues with this solution:

1. In this way the whole text is tappable which is not a big problem in my case but could be if the requirements are too strict for someone.
2. The bigger problem is: if you have to display more than one tappable part within the text, this solution is not able to do that. (At least I couldn't achieve that with your solution above.)

Unfortunately I've got an other situation where I have to make 2 parts tappable:

Screenshot 2022-05-03 at 17 04 15

**Comment by imodeveloper** [comment]
@merzal I explored a bit more, and the problem is in **ActiveLabel** highlightFontName, highlightFontSize It does not work properly with system fonts.

I created a fork and fixed that, now you can update the DSKit dependency package to `.package(url: "https://github.com/imodeveloperlab/ActiveLabel.swift", from: "1.1.7"),` in `Package.swift` 

and replace:
```swift
textView.highlightFontName = viewModel.linksFont?.getFont().fontName
textView.highlightFontSize = viewModel.linksFont?.getFont().pointSize
```
with:
```swift
textView.hightlightFont = viewModel.linksFont?.getFont()
```

and it will work ok with any font now. 

Also we need to have a test for this, so can you please update TypographyActiveTextVC

```swift 
var activeText = DSActiveTextVM(.body, text: "An astronomical term that's been coopted for colloquial #usage, nadir means the lowest point, as in the \"nadir of her popularity.\" Its @opposite term, noreply@dskit.com zenith, has a similar appeal.")

activeText.links = ["astronomical": "https://dskit.app"]

activeText.didTapOnHashTag = { tag in
    self.show(message: "Did tap on hashtag: #\(tag)")
}

activeText.didTapOnUrl = { url in
    self.show(message: "Did tap on url:\(url.absoluteString)")
}

activeText.didTapOnEmail = { email in
    self.show(message: "Did tap on email: \(email)")
}

activeText.didTapOnMention = { mention in
    self.show(message: "Did tap on mention: @\(mention)")
}

var activeText2 = DSActiveTextVM(.body, text: "By creating your account you agree to our Tersm of Use, and Privacy Policy.")
activeText2.links = ["Tersm of Use": "https://dskit.app", "Privacy Policy": "https://dskit.app"]
activeText2.linksFont = .headline
activeText2.alignment = .center

activeText2.didTapOnUrl = { url in
    self.show(message: "Did tap on url:\(url.absoluteString)")
}

show(content: activeText, activeText2)
```

and we will have this result: 
Screenshot 2022-05-04 at 09 36 44

and don't forget to update the snapshot image :)

**Comment by merzal** [comment]
Done. Please check if everything is OK now. And thank you for your help! :)

**Comment by imodeveloper** [comment]
Thank you for contribution!

**Pull request merged**
